name: npm-publish
on:
  push:
    branches:
      - master
jobs:
  npm-publish:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: |
        yarn
        # TODO: remove
        rm -r ./node_modules/higlass/dist
        cp -r ./higlass ./node_modules/higlass/dist
        cp ./higlass-register/index.js ./node_modules/higlass-register/src/index.js
        yarn build
    - uses: pascalgn/npm-publish-action@06e0830ea83eea10ed4a62654eeaedafb8bf50fc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}